trigger:
- main

pool:
  name: 'Mypool'

variables:
  resourceGroup: 'AZURE_WEBAPP'
  location: 'Central India'
  appServicePlan: 'mywebappdemo-plan'
  webAppName: 'mywebappdemo'

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(Build.SourcesDirectory)'
        includeRootFolder: false
        archiveFile: '$(Build.ArtifactStagingDirectory)/drop.zip'
        replaceExistingArchive: true

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

- stage: Deploy
  jobs:
  - job: DeployJob
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        artifact: drop
        path: $(Pipeline.Workspace)

    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AZURE_WEBAPP_SC'
        scriptType: ps
        scriptLocation: inlineScript
        inlineScript: |
          az group create -n $(resourceGroup) -l $(location)
          az appservice plan create -g $(resourceGroup) -n $(appServicePlan) --sku $(sku) --is-linux
          az webapp create -g $(resourceGroup) -p $(appServicePlan) -n $(webAppName) --runtime "PYTHON|3.9"
          az webapp deployment source config-zip -g $(resourceGroup) -n $(webAppName) --src $(Pipeline.Workspace)/drop/drop.zip