trigger:
- main   # pipeline runs whenever you push to main branch

pool:
  name: 'Mypool'

variables:
  resourceGroup: 'AZURE_WEBAPP'
  location: 'Central India'
  appName: 'mywebapp$(Build.BuildId)'

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(Build.SourcesDirectory)'
        includeRootFolder: false
        archiveFile: '$(Build.ArtifactStagingDirectory)/drop.zip'
        replaceExistingArchive: true

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

- stage: Deploy
  jobs:
  - job: DeployJob
    steps:
    - download: current
      artifact: drop

    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AZURE_WEBAPP_SC'   # Use your service connection name
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          # Create Resource Group if not exists
          az group create -n $(resourceGroup) -l $(location)

          # Create App Service Plan
          az appservice plan create -g $(resourceGroup) -n "$(appName)-plan" --sku FREE || true

          # Create Web App
          az webapp create -g $(resourceGroup) -p "$(appName)-plan" -n $(appName) --runtime "PYTHON:3.9" || true

          # Deploy the zip package
          az webapp deployment source config-zip \
            -g $(resourceGroup) -n $(appName) \
            --src $(Pipeline.Workspace)/drop/drop.zip

          echo "✅ Deployment complete! Visit: https://$(appName).azurewebsites.net"